version: '3.7'

services:
    database:
        image: postgres
        environment:
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: keycloak
        ports:
            - "5432:5432"
        volumes:
            - "storage:/var/lib/postgresql/data"
    keycloak:
        build: .
        environment:
            KEYCLOAK_ADMIN: admin
            KEYCLOAK_ADMIN_PASSWORD: Pa55w0rd
            PORT: 8123
            KC_DB_URL: jdbc:postgresql://database/keycloak
            KC_DB_USER: postgres
            KC_DB_PASSWORD: postgres
        ports:
            - "8123:8123"
        depends_on:
            - database

volumes:
    storage: